[package]
name = "scryer-prolog"
version = "0.9.0"
authors = ["Mark Thom <markjordanthom@gmail.com>"]
edition = "2021"
description = "A modern Prolog implementation written mostly in Rust."
readme = "README.md"
repository = "https://github.com/mthom/scryer-prolog"
license = "BSD-3-Clause"
keywords = ["prolog", "prolog-interpreter", "prolog-system"]
categories = ["command-line-utilities"]
build = "build/main.rs"
rust-version = "1.57"

[features]
num = ["num-rug-adapter"]
# no default features to make num tests work
# workaround for --no-default-features and --features not working intuitively for workspaces with a root package
# see rust-lang/cargo#7160
default = ["rug"]

[build]
rustflags = ["--cfg", "tokio_unstable"]

[build-dependencies]
indexmap = "1.0.2"
proc-macro2 = "1.0.36"
quote = "1.0.15"
strum = "0.23"
strum_macros = "0.23"
syn = { version = "1.0.88", features = ['full', 'visit', 'extra-traits'] }
to-syn-value = "0.1.0"
to-syn-value_derive = "0.1.0"
walkdir = "2"

[dependencies]
cpu-time = "1.0.0"
# crossterm = "0.20.0"
dirs-next = "2.0.0"
divrem = "0.1.0"
fxhash = "0.2.1"
git-version = "0.3.4"
# hostname = "0.3.1"
indexmap = "1.0.2"
lazy_static = "1.4.0"
lexical = "5.2.2"
libc = "0.2.62"
modular-bitfield = "0.11.2"
# ctrlc = "3.2.2"
num-rug-adapter = { version = "0.1.6", optional = true }
ordered-float = "2.6.0"
phf = { version = "0.9",  features = ["macros"] }
ref_thread_local = "0.0.0"
rug = { version = "1.15.0", optional = true }
# rustyline = "9.0.0"
# ring = "0.16.13"
ripemd160 = "0.8.0"
sha3 = "0.8.2"
blake2 = "0.8.1"
# openssl = { version = "0.10.29", features = ["vendored"] }
# native-tls = "0.2.4"
chrono = "0.4.11"
select = "0.4.3"
roxmltree = "0.11.0"
base64 = "0.12.3"
smallvec = "1.8.0"
# sodiumoxide = "0.2.6"
static_assertions = "1.1.0"
ryu = "1.0.9"
# hyper = { version = "0.14", features = ["full"] }
# hyper-tls = "0.5.0"
tokio = { version = "1", features = ["rt", "macros", "io-util"] }

[dev-dependencies]
assert_cmd = "1.0.3"
predicates-core = "1.0.2"
serial_test = "0.5.1"

[patch.crates-io]
modular-bitfield = { git = "https://github.com/mthom/modular-bitfield" }
num-rug-adapter = { git = "https://github.com/mthom/num-rug-adapter" }

[profile.release]
debug = true